[package]
name = "keylogger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inputbot = {git = "https://github.com/obv-mikhail/InputBot.git", rev="75593e4b93bb5411dcafe47f36b00a9eca98898b"}
